server:
  port: 8080
spring:
  profiles: prod
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:jhipster;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: true
    format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy